export const opportunityCandidates = [
  {
    title: 'Vyaire Medical',
    description: 'Fabricante global de soluciones respiratorias y ventilación; potencial de integración en flujos clínicos/homecare. Región principal: global (presencia EU/US). Web: https://www.vyaire.com. Contacto: https://www.vyaire.com/contact-us',
    marketProblem: 'Integración heterogénea entre datos de dispositivos respiratorios y sistemas clínicos-operativos.',
    proposedSolution: 'Partnership técnico para normalizar datos de dispositivos y habilitar workflows de seguimiento domiciliario.',
    technicalIntegration: 'API/exports + mapeo HL7/FHIR + paneles operativos para homecare.',
    potentialClients: ['Hospitales', 'Proveedores domiciliarios', 'Clínicas respiratorias'],
    technicalDifficulty: 'Media',
    businessPotential: 'Alto',
    barriers: 'Acceso a datos/partners técnicos y acuerdos enterprise.',
    validationSteps: 'Contactar BD, pedir documentación técnica y proponer piloto de interoperabilidad.',
    score: 8.1,
    tags: ['empresa', 'partnership', 'integración', 'fabricante'],
    sourceLinks: ['https://www.vyaire.com', 'https://www.vyaire.com/contact-us'],
  },
  {
    title: 'Löwenstein Medical',
    description: 'Especialista en ventilación y terapia respiratoria con fuerte presencia europea. Web: https://loewensteinmedical.com/en/. Contacto: https://loewensteinmedical.com/en/contact/',
    marketProblem: 'Necesidad de integrar telemonitorización y operación clínica en proveedores domiciliarios.',
    proposedSolution: 'Integración de datos y colaboración comercial para despliegues en homecare europeo.',
    technicalIntegration: 'Conectores API/export + FHIR/HL7 + dashboard de adherencia.',
    potentialClients: ['Homecare', 'Hospitales', 'Redes de neumología'],
    technicalDifficulty: 'Media',
    businessPotential: 'Alto',
    barriers: 'Dependencia de acuerdos comerciales y validación técnica por país.',
    validationSteps: 'Abrir canal con equipo de partnerships e identificar quick-win de integración.',
    score: 8.4,
    tags: ['empresa', 'partnership', 'integración', 'ventilación'],
    sourceLinks: ['https://loewensteinmedical.com/en/', 'https://loewensteinmedical.com/en/contact/'],
  },
  {
    title: 'Fisher & Paykel Healthcare',
    description: 'Fabricante relevante en respiratorio y cuidados domiciliarios con alcance internacional. Web: https://www.fphcare.com/. Contacto: https://www.fphcare.com/us/contact-us/',
    marketProblem: 'Falta de estandarización entre fabricantes para analítica y continuidad asistencial.',
    proposedSolution: 'Alianza para interoperabilidad y seguimiento terapéutico con integración en ecosistema provider.',
    technicalIntegration: 'API/exports, normalización de observaciones, integración con EMR mediante FHIR.',
    potentialClients: ['Hospitales', 'Proveedores domiciliarios', 'Aseguradoras'],
    technicalDifficulty: 'Media',
    businessPotential: 'Alto',
    barriers: 'Negociación enterprise y madurez de interfaces técnicas disponibles.',
    validationSteps: 'Solicitar capabilities técnicas y proponer piloto en cohortes de adherencia.',
    score: 8.2,
    tags: ['empresa', 'partnership', 'integración', 'CPAP'],
    sourceLinks: ['https://www.fphcare.com/', 'https://www.fphcare.com/us/contact-us/'],
  },
  {
    title: 'Dräger',
    description: 'Compañía alemana con soluciones respiratorias y monitorización clínica con footprint hospitalario y homecare indirecto. Web: https://www.draeger.com/. Contacto: https://www.draeger.com/en_corp/Contact',
    marketProblem: 'Integración parcial entre monitorización respiratoria y sistemas clínicos en continuidad hospital-domicilio.',
    proposedSolution: 'Partnership para integración de datos respiratorios y despliegue de paneles unificados clínico-operativos.',
    technicalIntegration: 'Integración por APIs/exportes + normalización HL7/FHIR + cuadros de mando de adherencia.',
    potentialClients: ['Hospitales', 'Proveedores domiciliarios'],
    technicalDifficulty: 'Alta',
    businessPotential: 'Alto',
    barriers: 'Ciclos enterprise y validación técnica multi-entorno.',
    validationSteps: 'Contacto con alianzas estratégicas y definición de caso de uso piloto.',
    score: 7.9,
    tags: ['empresa', 'partnership', 'integración', 'monitorización'],
    sourceLinks: ['https://www.draeger.com/', 'https://www.draeger.com/en_corp/Contact'],
  },
  {
    title: 'Nihon Kohden (Respiratory Solutions)',
    description: 'Fabricante global con tecnología de monitorización y soluciones respiratorias en entorno clínico. Web: https://www.nihonkohden.com/. Contacto: https://www.nihonkohden.com/contact/',
    marketProblem: 'Falta de continuidad de datos entre monitorización clínica y seguimiento respiratorio remoto.',
    proposedSolution: 'Integración de señales respiratorias en plataforma común para alertas y seguimiento domiciliario.',
    technicalIntegration: 'Conectores de datos, FHIR Observation/Device y export analítico.',
    potentialClients: ['Hospitales', 'Clínicas respiratorias'],
    technicalDifficulty: 'Media',
    businessPotential: 'Medio',
    barriers: 'Priorización comercial y acceso a interfaces técnicas específicas.',
    validationSteps: 'Reunión técnica/comercial y evaluación de APIs/exports disponibles.',
    score: 7.6,
    tags: ['empresa', 'partnership', 'integración', 'monitorización'],
    sourceLinks: ['https://www.nihonkohden.com/', 'https://www.nihonkohden.com/contact/'],
  },
  {
    title: 'DeVilbiss Healthcare',
    description: 'Actor relevante en terapias respiratorias domiciliarias (oxigenoterapia y equipos respiratorios). Web: https://www.devilbisshealthcare.com/. Contacto: https://www.devilbisshealthcare.com/contact-us/',
    marketProblem: 'Operación fragmentada en homecare con baja automatización de seguimiento y soporte.',
    proposedSolution: 'Colaboración para integrar datos de dispositivos y flujos de operación en una plataforma única.',
    technicalIntegration: 'Exports/API + capa de normalización y dashboards de servicio clínico.',
    potentialClients: ['Proveedores domiciliarios', 'Distribuidores respiratorios'],
    technicalDifficulty: 'Media',
    businessPotential: 'Medio',
    barriers: 'Dependencia de disponibilidad de interfaces digitales del fabricante.',
    validationSteps: 'Validar acceso técnico y diseñar piloto de integración con provider local.',
    score: 7.7,
    tags: ['empresa', 'partnership', 'integración', 'homecare'],
    sourceLinks: ['https://www.devilbisshealthcare.com/', 'https://www.devilbisshealthcare.com/contact-us/'],
  },
  {
    title: 'Apex Medical',
    description: 'Fabricante internacional de equipos respiratorios/sueño con presencia en varios mercados. Web: https://www.apexmedicalcorp.com/. Contacto: https://www.apexmedicalcorp.com/contact/',
    marketProblem: 'Necesidad de integración estandarizada para ampliar adopción en proveedores domiciliarios.',
    proposedSolution: 'Partner de integración para interoperar datos de terapia y métricas de adherencia.',
    technicalIntegration: 'Conectores de datos + mapeo FHIR + automatización de reporting clínico.',
    potentialClients: ['Homecare', 'Clínicas de sueño', 'Hospitales'],
    technicalDifficulty: 'Media',
    businessPotential: 'Medio',
    barriers: 'Disponibilidad de APIs y acuerdos de interoperabilidad.',
    validationSteps: 'Contacto BD y prueba técnica de extracción/normalización de datos.',
    score: 7.5,
    tags: ['empresa', 'partnership', 'integración', 'sleep'],
    sourceLinks: ['https://www.apexmedicalcorp.com/', 'https://www.apexmedicalcorp.com/contact/'],
  },
];
