export const opportunityCandidates = [
  {
    title: 'Vyaire Medical',
    description: 'Fabricante global de soluciones respiratorias y ventilación; potencial de integración en flujos clínicos/homecare. Región principal: global (presencia EU/US). Web: https://www.vyaire.com. Contacto: https://www.vyaire.com/contact-us',
    marketProblem: 'Integración heterogénea entre datos de dispositivos respiratorios y sistemas clínicos-operativos.',
    proposedSolution: 'Partnership técnico para normalizar datos de dispositivos y habilitar workflows de seguimiento domiciliario.',
    technicalIntegration: 'API/exports + mapeo HL7/FHIR + paneles operativos para homecare.',
    potentialClients: ['Hospitales', 'Proveedores domiciliarios', 'Clínicas respiratorias'],
    technicalDifficulty: 'Media',
    businessPotential: 'Alto',
    barriers: 'Acceso a datos/partners técnicos y acuerdos enterprise.',
    validationSteps: 'Contactar BD, pedir documentación técnica y proponer piloto de interoperabilidad.',
    score: 8.1,
    tags: ['empresa', 'partnership', 'integración', 'fabricante'],
    sourceLinks: ['https://www.vyaire.com', 'https://www.vyaire.com/contact-us'],
  },
  {
    title: 'Löwenstein Medical',
    description: 'Especialista en ventilación y terapia respiratoria con fuerte presencia europea. Web: https://loewensteinmedical.com/en/. Contacto: https://loewensteinmedical.com/en/contact/',
    marketProblem: 'Necesidad de integrar telemonitorización y operación clínica en proveedores domiciliarios.',
    proposedSolution: 'Integración de datos y colaboración comercial para despliegues en homecare europeo.',
    technicalIntegration: 'Conectores API/export + FHIR/HL7 + dashboard de adherencia.',
    potentialClients: ['Homecare', 'Hospitales', 'Redes de neumología'],
    technicalDifficulty: 'Media',
    businessPotential: 'Alto',
    barriers: 'Dependencia de acuerdos comerciales y validación técnica por país.',
    validationSteps: 'Abrir canal con equipo de partnerships e identificar quick-win de integración.',
    score: 8.4,
    tags: ['empresa', 'partnership', 'integración', 'ventilación'],
    sourceLinks: ['https://loewensteinmedical.com/en/', 'https://loewensteinmedical.com/en/contact/'],
  },
  {
    title: 'Fisher & Paykel Healthcare',
    description: 'Fabricante relevante en respiratorio y cuidados domiciliarios con alcance internacional. Web: https://www.fphcare.com/. Contacto: https://www.fphcare.com/us/contact-us/',
    marketProblem: 'Falta de estandarización entre fabricantes para analítica y continuidad asistencial.',
    proposedSolution: 'Alianza para interoperabilidad y seguimiento terapéutico con integración en ecosistema provider.',
    technicalIntegration: 'API/exports, normalización de observaciones, integración con EMR mediante FHIR.',
    potentialClients: ['Hospitales', 'Proveedores domiciliarios', 'Aseguradoras'],
    technicalDifficulty: 'Media',
    businessPotential: 'Alto',
    barriers: 'Negociación enterprise y madurez de interfaces técnicas disponibles.',
    validationSteps: 'Solicitar capabilities técnicas y proponer piloto en cohortes de adherencia.',
    score: 8.2,
    tags: ['empresa', 'partnership', 'integración', 'CPAP'],
    sourceLinks: ['https://www.fphcare.com/', 'https://www.fphcare.com/us/contact-us/'],
  },
];
